CREATE TABLE applications (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id          VARCHAR(40)     NOT NULL,
    idempotency_key         VARCHAR(100),
    applicant_id            VARCHAR(60)     NOT NULL,
    bond_type               VARCHAR(40)     NOT NULL,
    bond_amount             NUMERIC(15,2)   NOT NULL,
    effective_date          DATE            NOT NULL,
    obligee_name            VARCHAR(200)    NOT NULL,
    status                  VARCHAR(20)     NOT NULL,
    score                   INTEGER,
    decision                VARCHAR(20),
    score_breakdown_json    TEXT,
    applicant_snapshot_json TEXT,
    failure_reason          VARCHAR(500),
    attempt_count           INTEGER         NOT NULL DEFAULT 0,
    correlation_id          VARCHAR(60),
    created_at              TIMESTAMP       NOT NULL,
    updated_at              TIMESTAMP       NOT NULL,
    version                 BIGINT,

    CONSTRAINT uk_applications_business_id UNIQUE (application_id),
    CONSTRAINT uk_applications_idempotency_key UNIQUE (idempotency_key)
);

CREATE INDEX ix_applications_status ON applications (status);

CREATE TABLE notification_outbox (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id  VARCHAR(40)   NOT NULL,
    event_type      VARCHAR(60)   NOT NULL,
    payload_json    TEXT          NOT NULL,
    status          VARCHAR(20)   NOT NULL,
    attempt_count   INTEGER       NOT NULL DEFAULT 0,
    last_error      VARCHAR(500),
    next_attempt_at TIMESTAMP,
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL,
    version         BIGINT
);

CREATE INDEX ix_outbox_status ON notification_outbox (status);
