CREATE TABLE brokers (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broker_name   VARCHAR(200)  NOT NULL,
    client_id     VARCHAR(100)  NOT NULL,
    client_secret VARCHAR(200)  NOT NULL,
    scopes        VARCHAR(300)  NOT NULL,
    created_at    TIMESTAMP     NOT NULL,

    CONSTRAINT uk_brokers_client_id UNIQUE (client_id)
);

-- Two demo brokers: one for local development / the README's curl examples,
-- a second so tests (and you, manually) can prove one broker never sees
-- another's applications. {noop} is Spring Security's
-- DelegatingPasswordEncoder plaintext marker -- fine for seeded demo
-- credentials, never for a real broker's secret (use a "{bcrypt}..." hash
-- for those; see README for how to generate one).
INSERT INTO brokers (broker_name, client_id, client_secret, scopes, created_at) VALUES
    ('Demo Broker One', 'demo-broker-1', '{noop}demo-secret-1', 'applications.read,applications.write', CURRENT_TIMESTAMP),
    ('Demo Broker Two', 'demo-broker-2', '{noop}demo-secret-2', 'applications.read,applications.write', CURRENT_TIMESTAMP);

-- Nullable-then-backfill-then-NOT NULL, rather than adding it NOT NULL
-- directly: correct practice for a table that might already have rows in
-- some environment, even though on a fresh install applications is empty
-- and this backfill is a no-op.
ALTER TABLE applications ADD COLUMN broker_id VARCHAR(100);
UPDATE applications SET broker_id = 'unknown-legacy' WHERE broker_id IS NULL;
ALTER TABLE applications ALTER COLUMN broker_id SET NOT NULL;

CREATE INDEX ix_applications_broker_id ON applications (broker_id);
